# 
# Synthesis run script generated by Vivado
# 

set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a15tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.cache/wt [current_project]
set_property parent.project_path C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_ip -quiet C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property used_in_implementation false [get_files -all c:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc]
set_property is_locked true [get_files C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top mult_gen_0 -part xc7a15tftg256-1 -mode out_of_context

rename_ref -prefix_all mult_gen_0_

write_checkpoint -force -noxdef mult_gen_0.dcp

catch { report_utilization -file mult_gen_0_utilization_synth.rpt -pb mult_gen_0_utilization_synth.pb }

if { [catch {
  write_verilog -force -mode synth_stub C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

add_files C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0_stub.v -of_objects [get_files C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

add_files C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0_stub.vhdl -of_objects [get_files C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

add_files C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0_sim_netlist.v -of_objects [get_files C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

add_files C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0_sim_netlist.vhdl -of_objects [get_files C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

add_files C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0.dcp -of_objects [get_files C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

if {[file isdir C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.ip_user_files/ip/mult_gen_0]} {
  catch { 
    file copy -force C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0_sim_netlist.v C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.ip_user_files/ip/mult_gen_0
  }
}

if {[file isdir C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.ip_user_files/ip/mult_gen_0]} {
  catch { 
    file copy -force C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0_sim_netlist.vhdl C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.ip_user_files/ip/mult_gen_0
  }
}

if {[file isdir C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.ip_user_files/ip/mult_gen_0]} {
  catch { 
    file copy -force C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0_stub.v C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.ip_user_files/ip/mult_gen_0
  }
}

if {[file isdir C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.ip_user_files/ip/mult_gen_0]} {
  catch { 
    file copy -force C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.runs/mult_gen_0_synth_1/mult_gen_0_stub.vhdl C:/PROJECTS/STERN/96CH_RECORDER/FPGA/96mic/96mic.ip_user_files/ip/mult_gen_0
  }
}
